[tool.black]
line-length = 120
target-version = ["py311"]

[tool.mypy]
strict = true
python_version = "3.11"
junit_xml = "reports/mypy.xml"

[tool.ruff]
target-version = "py311"
line-length = 120
select = ["ALL"]
ignore = [
    "ANN101", # missing-type-self
    "COM", # trailing-comma
    "D", # documentation
    "T201", # print
    "INP001" # implicit-namespace-package
]
