name: Code analyse

on:
  workflow_call:

jobs:
  code-analyse:
    name: Code analyse
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install packages
        run: |
          sudo -E apt-get -qq update
          sudo apt install shellcheck
          pip install -r requirements-dev.txt

      - name: Check shell scripts
        run: |
          find . -type f -name "*.sh" -exec shellcheck --format=gcc {} \;

      - name: Lint with black
        run: |
          black --version
          black --diff --check $(git ls-files '*.py')

      - name: Lint with mypy
        run: |
          mypy --version
          mypy $(git ls-files '*.py')

      - name: Lint with ruff
        run: |
          ruff --version
          ruff $(git ls-files '*.py')

      - name: Lint with yamllint
        run: |
          yamllint --version
          yamllint $(git ls-files '*.yaml') $(git ls-files '*.yml')
