name: CI

on:
  workflow_dispatch:
    inputs:
      package-version:
        description: Version
        type: string
        required: True

env:
  PACKAGE_NAME: unipi-kernel-modules
  PACKAGE_VERSION: ${{ inputs.package-version }}
  REPO_URL: https://repo.unipi.technology/debian/pool/main/u/unipi-kernel-modules

jobs:
  code-analyse:
    name: Code analyse
    uses: ./.github/workflows/_code-analyse.yml

  get-dkms-source:
    name: Get DKMS source
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch'
      && github.ref == 'refs/heads/main'
    needs:
      - code-analyse

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download debian package
        shell: bash
        run: |
          ./.github/scripts/download-debian-package.sh
