name: CI

on:
  workflow_dispatch:
    inputs:
      package-version:
        description: Version
        type: string
        required: True

env:
  PACKAGE_NAME: unipi-kernel-modules-dkms
  PACKAGE_VERSION: ${{ inputs.package-version }}
  REPO_URL: https://repo.unipi.technology/debian/pool/main/u/unipi-kernel-modules

jobs:
  code-analyse:
    name: Code analyse
    uses: ./.github/workflows/_code-analyse.yml

  get-dkms-source:
    name: Get DKMS source
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch'
      && github.ref == 'refs/heads/main'
    needs:
      - code-analyse

    steps:
      - name: Export latest tag
        run: |
          echo "LATEST_TAG=$(curl -qsSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV

          echo $LATEST_TAG

      - name: Check version
        run: |
          ./.github/scripts/check-version.py

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download debian package
        shell: bash
        run: |
          ./.github/scripts/download-debian-package.sh

      - name: Uncompress debian package
        shell: bash
        run: |
          ./.github/scripts/uncompress-debian-package.sh

      - name: Commit kernel modules
        shell: bash
        run: |
          ./.github/scripts/commit-kernel-modules.sh

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.PACKAGE_VERSION }}
          body: Unipi kernel module v${{ env.PACKAGE_VERSION }}
          tag_name: refs/tags/v${{ env.PACKAGE_VERSION }}
