name: CI

on:
  workflow_dispatch:
    inputs:
      kernel-modules-version:
        description: Kernel version
        default: '2.26'
        type: string
        required: True

jobs:
  code-analyse:
    name: Code analyse
    uses: ./.github/workflows/_code-analyse.yml

  kernel-modules:
    name: Kernel modules
    uses: ./.github/workflows/_kernel-modules.yml
    with:
      kernel-modules-version: ${{ inputs.kernel-modules-version }}
